### ISSUE TITLE
Generate Demo Data Set for Rides

### ISSUE THREAD

**Issue by jamesward** [jamesward/koober#3]
A ride consists of:
- A driver
- A rider
- Location of Driver
- Location of Rider
- Time to pickup
- Time of event

In order to do #1 we need a demo data set we can feed into PredictionIO.  The data set can't be totally random otherwise our predictions might appear random.  So maybe there is public taxi data we can use.

**Comment by acheng96** [comment]
This NYC Cab data set looks promising: http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml

**Comment by jamesward** [comment]
Cool.  And I realized we don't really need the driver data for predicting demand, just the "request" or pickup data.

**Comment by adamwhat** [comment]
I'm making a sample of 2015 NYC Cab data set as the original data set is way too large for development. We can use the full data set to train the model once the whole pipeline is complete.

**Comment by adamwhat** [comment]
[https://s3-us-west-2.amazonaws.com/4740/yellow_tripdata_2015_all_sample.csv.zip
](Sample Data)

The sample is a 0.1% of the random sample with 1388068 entries from 2015 yellow cab dataset. 

[https://s3-us-west-2.amazonaws.com/4740/yellow_tripdata_2015_all_sample.pkl.zip](Here) is the HDS5 version of the same data. You can use [https://github.com/uchicago-cs/deepdish](deepdish) to load the data as a pandas DataFrame.

**Comment by jamesward** [comment]
Fixed by #4

**Comment by adamwhat** [comment]
https://s3-us-west-2.amazonaws.com/4740/yellow_tripdata_2015_further_sample.csv.zip

sample of 10000 lines of taxi data 2015
